name: Build and run tests

on: [push, pull_request]

jobs:  
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
           ${{ runner.os }}-node-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true

    - name: Log info
      run: | 
        echo ${{github.event_name}}
        echo ${{github.ref}}
        echo ${{github.head_ref}}
        echo ${{github.base_ref}}

    - name: Archive the build
      if: ${{github.event_name == 'pull_request' && github.head_ref == 'master'}}
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
