name: Deploy to Google Cloud Storage
on:
  push:
    branches:
      - master # Deployment will be triggered when we will push to the master branch

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true

    - name: Deploy to Google Cloud Storage
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '276.0.0'
        service_account_email: ${{secrets.GCP_SA_EMAIL}}
        service_account_key: ${{secrets.GCP_SA_KEY}}
    - run: gcloud app deploy
